---
title: "final_project"
author: "Dodjivi Amekoudji, Emily Lang, Jessica Marshall, Kat Vrotsos"
format: html
editor: visual
---

```{r}
# install.packages("here")
# install.packages("tidyverse")
library(here)
library(tidyverse)
```

# Load the data

```{r}
bmw_sales<- read_csv(here("data", "bmw_sales_data.csv"))
```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}
bmw_sales_decade <- bmw_sales %>% 
  filter(Year >= 2014)
```

```{r}

# filter to 2010–2024, select needed variables

bmw_price_sales <- bmw_sales %>%
select(Year, Price_USD, Sales_Volume, Fuel_Type) %>%
filter(Year >= 2010, Year <= 2024)

# summarize avg price and avg sales per year per fuel type

bmw_price_sales_summary <- bmw_price_sales %>%
group_by(Year, Fuel_Type) %>%
summarize(
avg_price = mean(Price_USD, na.rm = TRUE),
avg_sales = mean(Sales_Volume, na.rm = TRUE)
)

# visualize relationship btw price and sales volume

ggplot(bmw_price_sales_summary, aes(x = avg_price, y = avg_sales, color = Fuel_Type)) +
geom_line(linewidth = 1) +
geom_point(size = 2) +
labs(
title = "Relationship Between BMW Price and Sales Volume (2010–2024)",
x = "Average Price",
y = "Average Sales Volume",
color = "Fuel Type"
) +
theme_minimal()



```
